travis:
  secure:
    BINSTAR_TOKEN: lHsIU0cmM+bkDajbDZR7w6RD58OhUEhB2L6SlfVBXHP+coCGU355dXS6Ee6XjvPeaZJILU7mCN5yNmbhDep60N53Of5pLa3VQrhFM28ghTcuB22Rj8T3/pz1xRoAaAO9T7x4BgGXbleMkVsv1JRAs6XUDN4JdmzuE054t2ebBff4fhELM8+32riw2eJ2fEjRh9+wuNXwWQZfUWFBRHj+ECSSX50ogL+I4Vmvx3eCAIQnswCH6jG3dPfQOCEdrGf9fgJ6HqENlLNzIDDcAV/158QmkQRrXpHGzXZFB7yntIhTNJYDrFUP1YpJ7uXBaeoQBPAKzNM07MFqZFCHevla2KWZb2nPM/3v2GDtKkuz3Lp47sx+NtrdtF3zkqSAnlFuEcwn9gtQ+CYDjcQEKwMxAhac6xvWi+YQf8BTUBq1GIxorQgurdyN+YnW2cGUQaf99wq8lZO7FLUtwbmxG6yq00yqMkFktPxfRFWSaEUFk/5xtyvMsqYtmT9YraO2nDqfNPun0uEISWAHsr6quid93qTYB3SROi1ezDmQHDwGhL7CKvDx61YK/wyQfhnb3fioW3JFaLt6FoCuT8CdXHUGDLVN+QJLuoXEEMOReRxD9po8x6MHjrHyhkGhmiFacB32fAEqxaAbIyi34GI0JvQT//CPA04X654YBBpetn1duTw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
